### ISSUE TITLE
Gather Fonts, Logos, Icons

### ISSUE THREAD

**Issue by ghost** [bar0191/Denton-311#5]
Use fontawesome.com or others to find icons and logos/fonts.

**Comment by xbreid** [comment]
https://oblador.github.io/react-native-vector-icons/

**Comment by xbreid** [comment]
https://www.fonts.com/font/exljbris/museo-sans?QueryFontType=Web&src=GoogleWebFonts

**Comment by xbreid** [comment]
I've been using Ionicons for basic icons for now, we should probably find someone who can make graphics/assets for us
