### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by ghost** [bar0191/Denton-311#7]
Find color scheme and create palate

**Comment by GarrettCrowe** [comment]
UNT Green Hex: #00853E

**Comment by GarrettCrowe** [comment]
https://identityguide.unt.edu/create-our-look/color

**Comment by GarrettCrowe** [comment]
Complaint Yellow #eeac01

**Comment by xbreid** [comment]
http://paletton.com/#uid=3160u0kvStSkgB4pHwzyTnKENix
